[build]
builder = "NIXPACKS"
watchPatterns = [
  "src/**",
  "requirements.txt",
  "nixpacks.toml",
  "railway.toml"
]


[build.nixpacksConfig]
packages = [
  "unixODBC",
  "unixODBC-dev",
  "gcc",
  "g++",
  "curl",
  "gnupg"
]

[deploy]
startCommand = "python -m src.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
